In [7]:
from sklearn.datasets import load_digits
digits = load_digits()

In [8]:
print type(digits)
print digits.data

<class 'sklearn.datasets.base.Bunch'>
[[  0.   0.   5. ...,   0.   0.   0.]
 [  0.   0.   0. ...,  10.   0.   0.]
 [  0.   0.   0. ...,  16.   9.   0.]
 ..., 
 [  0.   0.   1. ...,   6.   0.   0.]
 [  0.   0.   2. ...,  12.   0.   0.]
 [  0.   0.  10. ...,  12.   1.   0.]]


In [10]:
print digits.DESCR

 Optical Recognition of Handwritten Digits Data Set

Notes
-----
Data Set Characteristics:
    :Number of Instances: 5620
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
http://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each block. This generates
an input matrix of 8x8 where each element is 

In [12]:
print digits.target

[0 1 2 ..., 8 9 8]


In [13]:
print digits.target_names

[0 1 2 3 4 5 6 7 8 9]


In [17]:
print type(digits.data)

<type 'numpy.ndarray'>


In [18]:
print type(digits.target)
print type(digits.target_names)

<type 'numpy.ndarray'>
<type 'numpy.ndarray'>


In [19]:
print digits.data.shape
print digits.target.shape

(1797, 64)
(1797,)


In [25]:
X = digits.data
y = digits.target

In [26]:
X

array([[  0.,   0.,   5., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,  10.,   0.,   0.],
       [  0.,   0.,   0., ...,  16.,   9.,   0.],
       ..., 
       [  0.,   0.,   1., ...,   6.,   0.,   0.],
       [  0.,   0.,   2., ...,  12.,   0.,   0.],
       [  0.,   0.,  10., ...,  12.,   1.,   0.]])

In [27]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [28]:
from sklearn import svm
clf = svm.SVC(gamma = 0.001, C = 100)
clf.fit(X,y)
print ('Prediction:'), clf.predict(digits.data[-1])
print ('Actual:'),y[-1]

Prediction: [8]
Actual: 8


In [29]:
print ('Prediction:'), clf.predict(digits.data[1])
print ('Actual:'),y[1]

Prediction: [1]
Actual: 1


# # Skull Dataset

In [30]:
import numpy as np
import pandas
from sklearn.neighbors import KNeighborsClassifier

In [31]:
my_data = pandas.read_csv("https://ibm.box.com/shared/static/exmvrr3eic0u6ete9zev5crwpjs0s295.csv",",")

In [32]:
my_data

Unnamed: 0    epoch   mb   bh   bl  nh
0             1  c4000BC  131  138   89  49
1             2  c4000BC  125  131   92  48
2             3  c4000BC  131  132   99  50
3             4  c4000BC  119  132   96  44
4             5  c4000BC  136  143  100  54
5             6  c4000BC  138  137   89  56
6             7  c4000BC  139  130  108  48
7             8  c4000BC  125  136   93  48
8             9  c4000BC  131  134  102  51
9            10  c4000BC  134  134   99  51
10           11  c4000BC  129  138   95  50
11           12  c4000BC  134  121   95  53
12           13  c4000BC  126  129  109  51
13           14  c4000BC  132  136  100  50
14           15  c4000BC  141  140  100  51
15           16  c4000BC  131  134   97  54
16           17  c4000BC  135  137  103  50
17           18  c4000BC  132  133   93  53
18           19  c4000BC  139  136   96  50
19           20  c4000BC  132  131  101  49
20           21  c4000BC  126  133  102  51
21           22  c4000BC  135  135  103  47
22           23  c4000BC  134  124   93  53
23           24  c4000BC  128  134  103  50
24           25  c4000BC  130  130  104  49
25           26  c4000BC  138  135  100  55
26           27  c4000BC  128  132   93  53
27           28  c4000BC  127  129  106  48
28           29  c4000BC  131  136  114  54
29           30  c4000BC  124  138  101  46
..          ...      ...  ...  ...  ...  ..
120         121   cAD150  137  123   91  50
121         122   cAD150  136  131   95  49
122         123   cAD150  128  126   91  57
123         124   cAD150  130  134   92  52
124         125   cAD150  138  127   86  47
125         126   cAD150  126  138  101  52
126         127   cAD150  136  138   97  58
127         128   cAD150  126  126   92  45
128         129   cAD150  132  132   99  55
129         130   cAD150  139  135   92  54
130         131   cAD150  143  120   95  51
131         132   cAD150  141  136  101  54
132         133   cAD150  135  135   95  56
133         134   cAD150  137  134   93  53
134         135   cAD150  142  135   96  52
135         136   cAD150  139  134   95  47
136         137   cAD150  138  125   99  51
137         138   cAD150  137  135   96  54
138         139   cAD150  133  125   92  50
139         140   cAD150  145  129   89  47
140         141   cAD150  138  136   92  46
141         142   cAD150  131  129   97  44
142         143   cAD150  143  126   88  54
143         144   cAD150  134  124   91  55
144         145   cAD150  132  127   97  52
145         146   cAD150  137  125   85  57
146         147   cAD150  129  128   81  52
147         148   cAD150  140  135  103  48
148         149   cAD150  147  129   87  48
149         150   cAD150  136  133   97  51

[150 rows x 6 columns]

In [33]:
print type(my_data)

<class 'pandas.core.frame.DataFrame'>


In [34]:
print my_data.columns
print my_data.values
print my_data.shape

Index([u'Unnamed: 0', u'epoch', u'mb', u'bh', u'bl', u'nh'], dtype='object')
[[1 'c4000BC' 131 138 89 49]
 [2 'c4000BC' 125 131 92 48]
 [3 'c4000BC' 131 132 99 50]
 [4 'c4000BC' 119 132 96 44]
 [5 'c4000BC' 136 143 100 54]
 [6 'c4000BC' 138 137 89 56]
 [7 'c4000BC' 139 130 108 48]
 [8 'c4000BC' 125 136 93 48]
 [9 'c4000BC' 131 134 102 51]
 [10 'c4000BC' 134 134 99 51]
 [11 'c4000BC' 129 138 95 50]
 [12 'c4000BC' 134 121 95 53]
 [13 'c4000BC' 126 129 109 51]
 [14 'c4000BC' 132 136 100 50]
 [15 'c4000BC' 141 140 100 51]
 [16 'c4000BC' 131 134 97 54]
 [17 'c4000BC' 135 137 103 50]
 [18 'c4000BC' 132 133 93 53]
 [19 'c4000BC' 139 136 96 50]
 [20 'c4000BC' 132 131 101 49]
 [21 'c4000BC' 126 133 102 51]
 [22 'c4000BC' 135 135 103 47]
 [23 'c4000BC' 134 124 93 53]
 [24 'c4000BC' 128 134 103 50]
 [25 'c4000BC' 130 130 104 49]
 [26 'c4000BC' 138 135 100 55]
 [27 'c4000BC' 128 132 93 53]
 [28 'c4000BC' 127 129 106 48]
 [29 'c4000BC' 131 136 114 54]
 [30 'c4000BC' 124 138 101 46]
 [31 'c3300BC' 1

In [35]:
def removeColumns(pandasArray, *column):
    return pandasArray.drop(pandasArray.columns[[column]],axis = 1).values

In [38]:
new_data = removeColumns(my_data,0,1)

In [39]:
new_data

array([[131, 138,  89,  49],
       [125, 131,  92,  48],
       [131, 132,  99,  50],
       [119, 132,  96,  44],
       [136, 143, 100,  54],
       [138, 137,  89,  56],
       [139, 130, 108,  48],
       [125, 136,  93,  48],
       [131, 134, 102,  51],
       [134, 134,  99,  51],
       [129, 138,  95,  50],
       [134, 121,  95,  53],
       [126, 129, 109,  51],
       [132, 136, 100,  50],
       [141, 140, 100,  51],
       [131, 134,  97,  54],
       [135, 137, 103,  50],
       [132, 133,  93,  53],
       [139, 136,  96,  50],
       [132, 131, 101,  49],
       [126, 133, 102,  51],
       [135, 135, 103,  47],
       [134, 124,  93,  53],
       [128, 134, 103,  50],
       [130, 130, 104,  49],
       [138, 135, 100,  55],
       [128, 132,  93,  53],
       [127, 129, 106,  48],
       [131, 136, 114,  54],
       [124, 138, 101,  46],
       [124, 138, 101,  48],
       [133, 134,  97,  48],
       [138, 134,  98,  45],
       [148, 129, 104,  51],
       [126, 1

In [47]:
def targetAndtargetNames(numpyArray, targetColumnIndex):
    target_dict = dict()
    target = list()
    target_names = list()
    count = -1
    for i in range(len(my_data.values)):
        if numpyArray.values[i][targetColumnIndex] not in target_dict:
            count += 1
            target_dict[numpyArray.values[i][targetColumnIndex]] = count
        target.append(target_dict[numpyArray.values[i][targetColumnIndex]])
    # Since a dictionary is not ordered, we need to order it and output it to a list so the
    # target names will match the target.
    for targetName in sorted(target_dict, key=target_dict.get):
        target_names.append(targetName)
    return np.asarray(target), target_names

In [48]:
target,target_names = targetAndtargetNames(my_data,1)

In [49]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [50]:
print(target_names)

['c4000BC', 'c3300BC', 'c1850BC', 'c200BC', 'cAD150']


In [52]:
X = new_data
y = target
neigh = KNeighborsClassifier(n_neighbors=1)
neigh.fit(X,y)
print('Prediction: '), neigh.predict(new_data[10])
print('Actual:'), y[10]

Prediction:  [0]
Actual: 0
